-- AlterTable
ALTER TABLE `Journal` ADD COLUMN `hasReminder` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `reminderTime` TIME NULL,
    ADD COLUMN `type` ENUM('NONE', 'DAILY') NOT NULL DEFAULT 'NONE';

-- AlterTable
ALTER TABLE `JournalEntry` ADD COLUMN `dayScore` INTEGER NULL,
    ADD COLUMN `emotion` ENUM('HAPPY', 'SAD', 'ANGRY', 'NEUTRAL', 'OVERWHELMED', 'FRUSTRATED', 'DEPRESSED', 'ANXIOUS', 'EXCITED', 'GOOD', 'TIRED') NULL;
