-- AlterTable
ALTER TABLE `JournalEntry` MODIFY `emotion` ENUM('HAPPY', 'SAD', 'ANGRY', 'NEUTRAL', 'OVERWHELMED', 'FRUSTRATED', 'DEPRESSED', 'ANXIOUS', 'EXCITED', 'GOOD', 'TIRED', 'MEH', 'ALRIGHT') NULL;
